# Generated by Django 2.2.9 on 2019-12-29 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191230_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='to_do_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
