# Generated by Django 2.2.9 on 2019-12-30 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191230_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='to_do_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
