# Generated by Django 2.2.9 on 2019-12-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191230_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='to_do_date',
        ),
    ]
