# Generated by Django 2.2.9 on 2019-12-30 19:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_task_to_do_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
